import Head from "next/head";
import Link from "next/link";
import { PrismaClient } from '@prisma/client';
import { api } from "~/utils/api";



export default function Home() {
  const data = api.post.getLatest.useQuery().data;
  return (
    <>
      <Head>
        <title>Welcome to Pono Points</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center min-h-screen bg-sussiest-forest bg-fixed bg-center bg-cover">
        <div className="flex self-center flex-col gap-20 bg-slate-500 rounded-xl p-20">

          <div className="flex self-center">
          <h1 className="font-mono tracking-tight text-white sm:text-[3.98rem]">
          Welcome to <span className="text-[hsl(70,80%,50%)]">Pono Points!</span>
          </h1>
        </div>

        <main className= "self-center grid grid-cols-2 gap-4 sm:grid-cols-2 md:gap-20 font-mono">

            <Link 
            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/25 p-4 text-white hover:bg-white/15 btn border-none w-auto h-auto"
            href="/login">
              <h3 className="text-2xl font-bold">Login</h3>
            </Link>

            <Link 
            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/25 p-4 text-white hover:bg-white/15 btn border-none w-auto h-auto"
            href="/SignUp">
              <h3 className="text-2xl font-bold">Sign Up</h3>
            </Link>
            </main>
           {data?.map(({id, content}) => (<div key = {id}>{content}</div>))}
        </div>
      </main>
    </>
  );
}