import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome to Pono Points</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center min-h-screen bg-sussy-forest bg-fixed bg-center bg-cover">
        <div className="flex self-center flex-col gap-20 bg-slate-500 rounded-xl p-20">
          <main className= "self-center grid grid-cols-2 gap-4 sm:grid-cols-2 md:gap-20 font-mono">

            <Link
              className=" flex max-w-xs flex-col gap-4 rounded-xl bg-white/25 p-4 text-white hover:bg-white/15 btn border-none w-auto h-auto"
              href="/Tasks"
            >
              <h3 className="text-2xl font-bold">Tasks →</h3>
              <div className="text-lg">
                Do your tasks to get Pono Points!
          
              </div>  
            </Link>

            <Link
              className="btn border-none w-auto h-auto flex max-w-xs flex-col gap-4 rounded-xl bg-white/25 p-4 text-white hover:bg-white/15"
              href="/Leaderboard"
            >
              <h3 className="text-2xl font-bold">Leaderboard →</h3>
              <div className="text-lg">
                See who's on top of the charts!
              </div>
            </Link>
          </main>

          <div className="flex self-center">
            <h1 className="font-mono tracking-tight text-white sm:text-[3.98rem] h-16">
            Currently At: <span className="text-[hsl(70,80%,50%)]">Hana</span>
            </h1>
          </div>

          <div className="flex self-center h-15 w-40">
            <figure><img src="https://pbs.twimg.com/media/FhzILjkXwAE0g_i.png" alt="Map Here"/></figure>
          </div>

          <main className="self-center grid grid-cols-2 gap-4 sm:grid-cols-2 md:gap-20 font-mono">
            <Link
              className="btn border-none w-auto h-auto flex max-w-xs flex-col gap-4 rounded-xl bg-white/25 p-4 text-white hover:bg-white/15"
              href="/RedeemPoints"
            >
              <h3 className="text-2xl font-bold">Redeem Points →</h3>
              <div className="text-lg">
                Use your Pono Points to get sweet rewards!
              </div>
            </Link>

            <Link
              className="btn border-none w-auto h-auto flex max-w-xs flex-col gap-4 rounded-xl bg-white/25 p-4 text-white hover:bg-white/15"
              href="/LevelUpInfo"
            >
              <h3 className="text-2xl font-bold">Level Up Info →</h3>
              <div className="text-lg">
                Learn how far you are from your next level!
              </div>
            </Link>
          </main>

        </div>
      </main>
    </>
  );
}