import Head from "next/head";
import Link from "next/link";

export default function FirstPost() {
    return (
      <>
      <Head>
        <title>Welcome to Pono Points</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <main className="flex justify-center min-h-screen bg-sussiester-forest bg-fixed bg-center bg-cover">
        <div className="flex self-center flex-col gap-20 bg-slate-500 rounded-xl p-20">
  
          <div className="flex self-center">
            <h1 className="font-mono tracking-tight text-white sm:text-[3.98rem]">
            <span className="text-[hsl(70,80%,50%)]">Login</span>
            </h1>
          </div>
          <div>
      <p>Enter Username:</p>
      <input type="text" onChange={(e) => console.log(e.target.value)} />
       </div>

       <div>
      <p>Enter Password:</p>
      <input type="password" name="password" onChange={(e) => console.log(e.target.value)} />
       </div>
  
  
          <main className="self-center grid grid-cols-2 gap-4 sm:grid-cols-2 md:gap-20 font-mono">
              <h3 className="text-2xl font-bold">Don't Have an Account? <Link href="/SignUp"> <span className="text-[hsl(70,80%,50%)]"> Sign Up! </span></Link></h3>
          </main>
  
        </div>
      </main>
    </>
    );
  }