import Head from "next/head";
import Link from 'next/link';
export default function FirstPost() {
  return (
    <>
    <Head>
      <title>Welcome to Pono Points</title>
      <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>

  <main className="flex justify-center min-h-screen bg-sussy-forest bg-fixed bg-center bg-cover">
    <div className="flex self-center flex-col gap-20 bg-slate-500 rounded-xl p-20">

      <div className="flex self-center">
        <h1 className="font-mono tracking-tight text-white sm:text-[3.98rem]">
        Redeem your <span className="text-[hsl(70,80%,50%)]">Rewards &nbsp;&nbsp;</span>
        </h1>
      </div>

      <div className="font-mono tracking-tight text-white sm:text-[1.25rem]">
      <br/>
    <h3><input type="checkbox" aria-label="$10 Walmart Gift card: 1,000 points" className="btn border-none w-auto h-auto flex max-w-xs flex-col gap-4 rounded-xl bg-white/25 p-4 text-white hover:bg-white/15"/></h3>
    <br/>
    <h2><input type="checkbox" aria-label="$10 GameStop Gift Card: 1,000 points" className="btn btn border-none w-auto h-auto flex max-w-xs flex-col gap-4 rounded-xl bg-white/25 p-4 text-white hover:bg-white/15"/></h2>
    <br/>
    <h2><input type="checkbox" aria-label="$10 Home Depot Gift Card: 1,000 points" className="btn btn border-none w-auto h-auto flex max-w-xs flex-col gap-4 rounded-xl bg-white/25 p-4 text-white hover:bg-white/15"/></h2>
    <br/>
    <h2><input type="checkbox" aria-label="$10 Radio Shack Gift Card: 1,000 points" className="btn btn border-none w-auto h-auto flex max-w-xs flex-col gap-4 rounded-xl bg-white/25 p-4 text-white hover:bg-white/15"/></h2>
    <br/>
    <button className="btn rounded-full border-none w-auto h-auto flex max-w-xs flex-col gap-4 rounded-xl bg-white/25 p-4 text-white hover:bg-white/15">Click to submit</button>
      </div>

      <main className="self-center grid grid-cols-2 gap-4 sm:grid-cols-2 md:gap-20 font-mono">

        <Link
          className="btn border-none w-auto h-auto flex max-w-xs flex-col gap-4 rounded-xl bg-white/25 p-4 text-white hover:bg-white/15"
          href="/Lobby"
        >
          <h3 className="text-2xl font-bold">Back to Lobby →</h3>
        </Link>
      </main>

    </div>
  </main>
  </>
  );
}

/*<div style={{ fontSize: 15 }}> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Your Current Points: {points}</div>
<div style={{ fontSize: 50}}>Redeem Points</div>
<div><input type="checkbox" aria-label="$10 Walmart Gift card: 1,000 points" className="btn"/></div>
  <br></br>
  <h2><input type="checkbox" aria-label="$10 GameStop Gift Card: 1,000 points" className="btn"/></h2>
  <br></br>
  <h2><input type="checkbox" aria-label="$10 Home Depot Gift Card: 1,000 points" className="btn"/></h2>
  <br></br>
  <h2><input type="checkbox" aria-label="$10 Radio Shack Gift Card: 1,000 points" className="btn"/></h2>
  <button className="btn w-64 rounded-full">Click to submit</button>
  <br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br>
  <h2><Link href="/">Back to Lobby</Link></h2>
</>*/